//
//  YTCaption.swift
//
//
//  Created by Antoine Bollengier on 27.06.2024.
//  Copyright © 2024 - 2026 Antoine Bollengier (github.com/b5i). All rights reserved.
//

import Foundation

public struct YTCaption: Codable, Hashable, Identifiable, Sendable {
    /// Stable identifier from the player response when available.
    public var id: String

    public var languageCode: String
    
    public var languageName: String
    
    public var url: URL
    
    public var isTranslated: Bool

    /// Whether the source track was generated by automatic speech recognition.
    public var isAutoGenerated: Bool
    
    public init(
        languageCode: String,
        languageName: String,
        url: URL,
        isTranslated: Bool,
        id: String? = nil,
        isAutoGenerated: Bool = false
    ) {
        self.id = id ?? [
            isTranslated ? "translated" : "source",
            languageCode
        ].joined(separator: ":")
        self.languageCode = languageCode
        self.languageName = languageName
        self.url = url
        self.isTranslated = isTranslated
        self.isAutoGenerated = isAutoGenerated
    }
}
